version: '3'
services:
  db:
    container_name: system_db
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=topsecret
      - MYSQL_DATABASE=development
      - MYSQL_USER=devuser
      - MYSQL_PASSWORD=secure
    ports:
      - "3306:3306"
    volumes:
      - ../Docker/mysql/mycustom.cnf:/etc/mysql/conf.d/custom.cnf